"""Unattended validation schedule with explicit normal/recovery gaps."""
import argparse
import asyncio
import json
import time
from datetime import datetime, timezone
from pathlib import Path
import httpx


SCHEDULE = [
    # Minute 0–20 is normal; traffic.py adds a healthy surge at minute 10–15.
    {"at_minute": 20, "name": "slow-response", "duration_seconds": 180,
     "delay_ms": 600},
    {"at_minute": 31, "name": "gradual-latency", "duration_seconds": 240,
     "delay_ms": 700},
    {"at_minute": 43, "name": "error-burst", "duration_seconds": 180,
     "error_probability": .20},
    {"at_minute": 54, "name": "memory-growth", "duration_seconds": 300,
     "step_mib": 2, "cap_mib": 64},
    {"at_minute": 67, "name": "combined-degradation", "duration_seconds": 180,
     "delay_ms": 400, "error_probability": .10},
]

TEST_SCHEDULE = [
    {"at_minute": 20, "name": "slow-response", "duration_seconds": 180,
     "delay_ms": 350},
    {"at_minute": 31, "name": "gradual-latency", "duration_seconds": 240,
     "delay_ms": 500},
    {"at_minute": 43, "name": "error-burst", "duration_seconds": 180,
     "error_probability": .12},
    {"at_minute": 54, "name": "memory-growth", "duration_seconds": 300,
     "step_mib": 1, "cap_mib": 48},
    {"at_minute": 67, "name": "combined-degradation", "duration_seconds": 180,
     "delay_ms": 250, "error_probability": .07},
]


def write_status(path, payload):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix+".tmp")
    temporary.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    temporary.replace(path)


async def run_schedule(url, output, time_scale=1.0, schedule=None, kind="validation"):
    if not 0 < time_scale <= 1:
        raise ValueError("time-scale must be >0 and <=1")
    schedule = schedule or SCHEDULE
    started = time.monotonic()
    status = {
        "stage": "running", "started_at": datetime.now(timezone.utc).isoformat(),
        "time_scale": time_scale, "kind": kind, "schedule": schedule, "events": [],
        "note": "Healthy surge is generated by the validation-cycle traffic profile at minute 10–15.",
    }
    write_status(output, status)
    async with httpx.AsyncClient(base_url=url.rstrip("/"), timeout=5, trust_env=False) as client:
        for planned in schedule:
            target = started+planned["at_minute"]*60*time_scale
            await asyncio.sleep(max(0, target-time.monotonic()))
            payload = {key: value for key, value in planned.items() if key != "at_minute"}
            payload["duration_seconds"] *= time_scale
            response = await client.post("/dev/scenario", json=payload)
            response.raise_for_status()
            status["events"].append({
                "planned": planned, "started": response.json(),
                "triggered_at": datetime.now(timezone.utc).isoformat(),
            })
            write_status(output, status)
        last = schedule[-1]
        finish = started+(last["at_minute"]*60+last["duration_seconds"])*time_scale
        await asyncio.sleep(max(0, finish-time.monotonic()))
        # Confirm backend ended the final fault; allow sampler/tick scheduling tolerance.
        for _ in range(20):
            snapshot = (await client.get("/dev/scenario")).json()
            if snapshot["active"] is None:
                break
            await asyncio.sleep(.25)
        else:
            raise RuntimeError("Final validation scenario did not expire")
    status.update(stage="complete", finished_at=datetime.now(timezone.utc).isoformat())
    write_status(output, status)
    return status


def main():
    parser = argparse.ArgumentParser(description="Run the bounded validation fault schedule")
    parser.add_argument("--url", default="http://127.0.0.1:8010")
    parser.add_argument("--out", required=True)
    parser.add_argument("--time-scale", type=float, default=1.0,
                        help="Development/test only; production validation uses 1.0")
    parser.add_argument("--kind", choices=["validation", "test"], default="validation")
    args = parser.parse_args()
    try:
        schedule = TEST_SCHEDULE if args.kind == "test" else SCHEDULE
        asyncio.run(run_schedule(args.url, args.out, args.time_scale, schedule, args.kind))
    except Exception as exc:
        try:
            current = json.loads(Path(args.out).read_text(encoding="utf-8"))
        except Exception:
            current = {}
        current.update(stage="failed", failed_at=datetime.now(timezone.utc).isoformat(),
                       error=str(exc))
        write_status(args.out, current)
        raise


if __name__ == "__main__":
    main()
